### ISSUE TITLE
Spell chariot of ice Crash

### ISSUE THREAD

**Issue by omerbadawy11** [Electroblob77/TF-Spell-Pack#12] opened 2020-05-22 18:43 UTC
[latest.log](https://github.com/Electroblob77/TF-Spell-Pack/files/4669802/latest.log)

I can provide the Debug.log as well if it helps

**Comment by Electroblob77** [comment] 2020-05-24 16:19
Duplicate of #7.

**Closed as completed by Electroblob77** 2020-05-24 16:19 UTC
Labels: duplicate
